#!/usr/bin/env python3

import re

#Y can be C or T
#R can be A or G

fasta_open = open('Python_07_ApoI.fasta', 'r')

fragments = []

for line in fasta_open:
    line = line.rstrip()
    if not line.startswith('>'):
        cutSites = re.sub(r'[A|G]AATT[C|T]', r'R^AATTY', line)
        #fragments.append(cutSites.split('^'))
        fragments += cutSites.split('^')

print(sorted(fragments, key = len))

print("Script has finished.")
